/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as LogsLogsRouteImport } from './routes/logs/_logs'
import { Route as LogsLogsIndexRouteImport } from './routes/logs/_logs/index'
import { Route as LogsLogsLogIdRouteImport } from './routes/logs/_logs/$logId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsLogsRoute = LogsLogsRouteImport.update({
  id: '/logs/_logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsLogsIndexRoute = LogsLogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogsLogsRoute,
} as any)
const LogsLogsLogIdRoute = LogsLogsLogIdRouteImport.update({
  id: '/$logId',
  path: '/$logId',
  getParentRoute: () => LogsLogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs': typeof LogsLogsRouteWithChildren
  '/settings/': typeof SettingsIndexRoute
  '/logs/$logId': typeof LogsLogsLogIdRoute
  '/logs/': typeof LogsLogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsIndexRoute
  '/logs/$logId': typeof LogsLogsLogIdRoute
  '/logs': typeof LogsLogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logs/_logs': typeof LogsLogsRouteWithChildren
  '/settings/': typeof SettingsIndexRoute
  '/logs/_logs/$logId': typeof LogsLogsLogIdRoute
  '/logs/_logs/': typeof LogsLogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/logs' | '/settings/' | '/logs/$logId' | '/logs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/logs/$logId' | '/logs'
  id:
    | '__root__'
    | '/'
    | '/logs/_logs'
    | '/settings/'
    | '/logs/_logs/$logId'
    | '/logs/_logs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsLogsRoute: typeof LogsLogsRouteWithChildren
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/_logs': {
      id: '/logs/_logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/_logs/': {
      id: '/logs/_logs/'
      path: '/'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsLogsIndexRouteImport
      parentRoute: typeof LogsLogsRoute
    }
    '/logs/_logs/$logId': {
      id: '/logs/_logs/$logId'
      path: '/$logId'
      fullPath: '/logs/$logId'
      preLoaderRoute: typeof LogsLogsLogIdRouteImport
      parentRoute: typeof LogsLogsRoute
    }
  }
}

interface LogsLogsRouteChildren {
  LogsLogsLogIdRoute: typeof LogsLogsLogIdRoute
  LogsLogsIndexRoute: typeof LogsLogsIndexRoute
}

const LogsLogsRouteChildren: LogsLogsRouteChildren = {
  LogsLogsLogIdRoute: LogsLogsLogIdRoute,
  LogsLogsIndexRoute: LogsLogsIndexRoute,
}

const LogsLogsRouteWithChildren = LogsLogsRoute._addFileChildren(
  LogsLogsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsLogsRoute: LogsLogsRouteWithChildren,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
